-- Proyecto: Análisis de Cumplimiento SLA – CLRM03
-- Descripción: Consulta para calcular el cumplimiento de SLA por subproceso logístico en el centro CLRM03

WITH WA AS (
  SELECT
    OB.ENTITY_ID,
    OB.LOGISTIC_CENTER_ID,
    OB.SUB_CHANNEL AS SUBCA,
    OB.PROCESS_PATH_CODE,
    OB.OUTBOUND_DEPARTURE_ESTIMATED_DATE,
    OB.CREATED_DATE,
    CASE 
      WHEN OB.OUTBOUND_DEPARTURE_ESTIMATED_DATE < TIMESTAMP('2025-04-04T23:50:50') THEN OB.OUTBOUND_DEPARTURE_ESTIMATED_DATE
      ELSE TIMESTAMP_SUB(OB.OUTBOUND_DEPARTURE_ESTIMATED_DATE, INTERVAL 4 HOUR)
    END AS ETD,
    OOT.CTP_DATE,
    FM.WAVING_END_DATE,
    FM.PICKING_END_DATE,
    FM.PACKING_END_DATE,
    FM.DISPATCH_END_DATE
  FROM `meli-bi-data.WHOWNER.BT_SHP_MT_OUTBOUND` OB
  LEFT JOIN `meli-bi-data.WHOWNER.DM_SLA_OUTBOUND_DEEP_DIVE_OOT` OOT
    ON OB.ENTITY_ID = OOT.ENTITY_ID
  LEFT JOIN `meli-bi-data.WHOWNER.BT_SHP_MT_FOS_METRICS` FM
    ON OB.ENTITY_ID = FM.ENTITY_ID
  WHERE OB.LOGISTIC_CENTER_ID = 'CLRM03'
),

REGLAS AS (
  SELECT *,
    CASE 
      WHEN PROCESS = 'waving' THEN WAVING_END_DATE <= DATETIME_SUB(ETD, INTERVAL 360 MINUTE)
      WHEN PROCESS = 'picking' THEN PICKING_END_DATE <= DATETIME_SUB(ETD, INTERVAL 240 MINUTE)
      WHEN PROCESS = 'packing' THEN PACKING_END_DATE <= DATETIME_SUB(ETD, INTERVAL 180 MINUTE)
      WHEN PROCESS = 'dispatch' THEN DISPATCH_END_DATE <= DATETIME_SUB(ETD, INTERVAL 60 MINUTE)
      ELSE NULL
    END AS SLA_OK
  FROM WA,
  UNNEST(['waving', 'picking', 'packing', 'dispatch']) AS PROCESS
),

RESUMEN AS (
  SELECT
    PROCESS,
    FORMAT_DATE('%Y-%W', DATE(ETD)) AS SEMANA,
    COUNT(*) AS TOTAL,
    COUNTIF(SLA_OK) AS CUMPLE,
    ROUND(COUNTIF(SLA_OK) / COUNT(*) * 100, 2) AS SLA_PCT
  FROM REGLAS
  GROUP BY 1, 2
)

SELECT * FROM RESUMEN
ORDER BY SEMANA, PROCESS;
